name: Update Version on Docker Files

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  POSTGRES_VERSION: ${{ github.event.inputs.postgres_version }}
on:
  workflow_dispatch:
    inputs:
      project_version:
        description: "Version number to be released e.g 10.0.3"
      postgres_version:
        required: false
        description: "Postgres version number. If it is empty, postgres version will not be changed"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install package dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: Clone tools branch
        run: git clone -b v0.8.0 --depth=1  https://github.com/citusdata/tools.git tools

      - name: Print postgres version
        run: echo "${POSTGRES_VERSION}"

      - name: Update docker files
        run: |
          if [ -z "${POSTGRES_VERSION}" ] then \
            echo "Postgres Empty" \
          else \
           echo "Postgres not Empty" \
          fi
